/***************************************************************************
 *                                                                         *
 *   PROXCLIP.H  --  Proxy Client IP                                       *
 *                                                                         *
 *   A companion module for BBSFirewall on The Major BBS v10               *
 *                                                                         *
 *   PROXCLIP is developed and maintained by Mark Laudenbach               *
 *   at Sysop Network.                                                     *
 *                                                                         *
 *   Copyright (c) 2026 Sysop Network.  All Rights Reserved.              *
 *                                                                         *
 ***************************************************************************/

#ifndef __PROXCLIP_H
#define __PROXCLIP_H

#endif /* __PROXCLIP_H */
